version: "3.8"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard_home
    restart: unless-stopped
    ports:
      - "3000:3000"     # Web UI
      - "53:53/tcp"     # DNS (TCP)
      - "53:53/udp"     # DNS (UDP)
      - "67:67/udp"     # DHCP (falls aktiviert)
      - "853:853/tcp"   # DNS-over-TLS
      - "80:80"         # HTTP (optional, falls benötigt)
    volumes:
      - /docker/adguardhome/work:/opt/adguardhome/work
      - /docker/adguardhome/conf:/opt/adguardhome/conf
    environment:
      TZ: "Europe/Berlin" # Zeitzone anpassen
